Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "libvirt" do |lv|
    lv.memory = "2048"
    lv.default_prefix = "deb-buster64-libvirt"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define :mongodb42 do |mongodb42|
      mongodb42.vm.hostname = "deb-buster64-mongodb-42-libvirt"
      mongodb42.vm.network "private_network", ip: "192.168.10.200"
      mongodb42.vm.provision "shell", path: "../scripts/fix_libvirt.sh"
      mongodb42.vm.provision "file", source: "../scripts/mongod.conf", destination: "/tmp/mongod.conf"
      mongodb42.vm.provision "file", source: "../scripts/add_mongo_admin.js", destination: "/tmp/add_mongo_admin.js"
      mongodb42.vm.provision "file", source: "../scripts/update.sh", destination: "/tmp/update.sh"
      mongodb42.vm.provision "shell", path: "../scripts/install_mongodb-4.2.sh"
  end

  config.vm.define :nodejs12 do |nodejs12|
      nodejs12.vm.hostname = "deb-buster64-nodejs-12-libvirt"
      nodejs12.vm.network "private_network", ip: "192.168.10.230"
      nodejs12.vm.provision "shell", path: "../scripts/fix_libvirt.sh"
      nodejs12.vm.provision "file", source: "../scripts/update.sh", destination: "/tmp/update.sh"
      nodejs12.vm.provision "shell", path: "../scripts/install_node-12.x.sh"
  end
end
