Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "deb-buster64-nodejs-12-vbox"
  config.vm.network "private_network", ip: "192.168.10.230"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "deb-buster64-nodejs-12-vbox"
  end
  config.vm.provision "file", source: "../scripts/update.sh", destination: "/tmp/update.sh"
  config.vm.provision "shell", path: "../scripts/install_node-12.x.sh"
end
