Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "nodejs-10-vbox"
  config.vm.network "private_network", ip: "192.168.10.230"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "bionic-nodejs-10"
  end
  config.vm.provision "file", source: "../scripts/update.sh", destination: "/tmp/update.sh"
  config.vm.provision "shell", path: "../scripts/install_node-10.x.sh"
end
